name: Build KeyTotem Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and Unzip Source Code
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -type f -name "*.zip" | head -n 1)
          if [ -f "$ZIP_FILE" ]; then
            echo "==> Found source zip: $ZIP_FILE. Unzipping now..."
            unzip -o "$ZIP_FILE" -d .
            echo "==> Unzip complete."
          else
            echo "==> No .zip file found in root. Building with existing files."
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # NEW: This step removes Windows-style line endings that can break the script.
      - name: Fix gradlew line endings
        run: sed -i 's/\r$//' ./gradlew

      # This step makes the script runnable.
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # The --stacktrace flag is added for better error logging.
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyTotem-1.21.5-Build
          path: build/libs/!(*-dev|*-sources).jar
